// Mocks generated by Mockito 5.3.2 from annotations
// in submission/test/ui/views/detail/view/detail_view_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i11;
import 'dart:ui' as _i12;

import 'package:mockito/mockito.dart' as _i1;
import 'package:submission/core/constant/network_state.dart' as _i9;
import 'package:submission/domain/entities/movie.dart' as _i10;
import 'package:submission/domain/entities/movie_detail.dart' as _i7;
import 'package:submission/domain/usecases/get_detail_movie.dart' as _i2;
import 'package:submission/domain/usecases/get_recommended_movies.dart' as _i3;
import 'package:submission/domain/usecases/get_watchlist_movie_exist_status.dart'
    as _i4;
import 'package:submission/domain/usecases/remove_watchlist_movie.dart' as _i6;
import 'package:submission/domain/usecases/save_watchlist_movie.dart' as _i5;
import 'package:submission/ui/views/detail/detail_provider.dart' as _i8;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeGetDetailMovie_0 extends _i1.SmartFake
    implements _i2.GetDetailMovie {
  _FakeGetDetailMovie_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeGetRecommendedMovies_1 extends _i1.SmartFake
    implements _i3.GetRecommendedMovies {
  _FakeGetRecommendedMovies_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeGetWatchlistMovieExistStatus_2 extends _i1.SmartFake
    implements _i4.GetWatchlistMovieExistStatus {
  _FakeGetWatchlistMovieExistStatus_2(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeSaveWatchlistMovie_3 extends _i1.SmartFake
    implements _i5.SaveWatchlistMovie {
  _FakeSaveWatchlistMovie_3(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeRemoveWatchlistMovie_4 extends _i1.SmartFake
    implements _i6.RemoveWatchlistMovie {
  _FakeRemoveWatchlistMovie_4(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeMovieDetail_5 extends _i1.SmartFake implements _i7.MovieDetail {
  _FakeMovieDetail_5(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [DetailProvider].
///
/// See the documentation for Mockito's code generation for more information.
class MockDetailProvider extends _i1.Mock implements _i8.DetailProvider {
  MockDetailProvider() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.GetDetailMovie get getDetailMovie => (super.noSuchMethod(
        Invocation.getter(#getDetailMovie),
        returnValue: _FakeGetDetailMovie_0(
          this,
          Invocation.getter(#getDetailMovie),
        ),
      ) as _i2.GetDetailMovie);
  @override
  _i3.GetRecommendedMovies get getRecommendationsMovies => (super.noSuchMethod(
        Invocation.getter(#getRecommendationsMovies),
        returnValue: _FakeGetRecommendedMovies_1(
          this,
          Invocation.getter(#getRecommendationsMovies),
        ),
      ) as _i3.GetRecommendedMovies);
  @override
  _i4.GetWatchlistMovieExistStatus get getWatchlistExist => (super.noSuchMethod(
        Invocation.getter(#getWatchlistExist),
        returnValue: _FakeGetWatchlistMovieExistStatus_2(
          this,
          Invocation.getter(#getWatchlistExist),
        ),
      ) as _i4.GetWatchlistMovieExistStatus);
  @override
  _i5.SaveWatchlistMovie get saveWatchlist => (super.noSuchMethod(
        Invocation.getter(#saveWatchlist),
        returnValue: _FakeSaveWatchlistMovie_3(
          this,
          Invocation.getter(#saveWatchlist),
        ),
      ) as _i5.SaveWatchlistMovie);
  @override
  _i6.RemoveWatchlistMovie get removeWatchlist => (super.noSuchMethod(
        Invocation.getter(#removeWatchlist),
        returnValue: _FakeRemoveWatchlistMovie_4(
          this,
          Invocation.getter(#removeWatchlist),
        ),
      ) as _i6.RemoveWatchlistMovie);
  @override
  String get message => (super.noSuchMethod(
        Invocation.getter(#message),
        returnValue: '',
      ) as String);
  @override
  _i9.RequestState get detailState => (super.noSuchMethod(
        Invocation.getter(#detailState),
        returnValue: _i9.RequestState.initial,
      ) as _i9.RequestState);
  @override
  _i7.MovieDetail get detailMovie => (super.noSuchMethod(
        Invocation.getter(#detailMovie),
        returnValue: _FakeMovieDetail_5(
          this,
          Invocation.getter(#detailMovie),
        ),
      ) as _i7.MovieDetail);
  @override
  _i9.RequestState get recommendationState => (super.noSuchMethod(
        Invocation.getter(#recommendationState),
        returnValue: _i9.RequestState.initial,
      ) as _i9.RequestState);
  @override
  List<_i10.Movie> get recommendedMovies => (super.noSuchMethod(
        Invocation.getter(#recommendedMovies),
        returnValue: <_i10.Movie>[],
      ) as List<_i10.Movie>);
  @override
  String get watchlistMessage => (super.noSuchMethod(
        Invocation.getter(#watchlistMessage),
        returnValue: '',
      ) as String);
  @override
  bool get hasAddedToWatchlist => (super.noSuchMethod(
        Invocation.getter(#hasAddedToWatchlist),
        returnValue: false,
      ) as bool);
  @override
  bool get hasListeners => (super.noSuchMethod(
        Invocation.getter(#hasListeners),
        returnValue: false,
      ) as bool);
  @override
  _i11.Future<void> loadMovieDetail(int? id) => (super.noSuchMethod(
        Invocation.method(
          #loadMovieDetail,
          [id],
        ),
        returnValue: _i11.Future<void>.value(),
        returnValueForMissingStub: _i11.Future<void>.value(),
      ) as _i11.Future<void>);
  @override
  _i11.Future<void> loadRecommendedMovie(int? id) => (super.noSuchMethod(
        Invocation.method(
          #loadRecommendedMovie,
          [id],
        ),
        returnValue: _i11.Future<void>.value(),
        returnValueForMissingStub: _i11.Future<void>.value(),
      ) as _i11.Future<void>);
  @override
  _i11.Future<void> addWatchlist(_i7.MovieDetail? movie) => (super.noSuchMethod(
        Invocation.method(
          #addWatchlist,
          [movie],
        ),
        returnValue: _i11.Future<void>.value(),
        returnValueForMissingStub: _i11.Future<void>.value(),
      ) as _i11.Future<void>);
  @override
  _i11.Future<void> removeFromWatchlist(_i7.MovieDetail? movie) =>
      (super.noSuchMethod(
        Invocation.method(
          #removeFromWatchlist,
          [movie],
        ),
        returnValue: _i11.Future<void>.value(),
        returnValueForMissingStub: _i11.Future<void>.value(),
      ) as _i11.Future<void>);
  @override
  _i11.Future<void> loadWatchlistExistStatus(int? id) => (super.noSuchMethod(
        Invocation.method(
          #loadWatchlistExistStatus,
          [id],
        ),
        returnValue: _i11.Future<void>.value(),
        returnValueForMissingStub: _i11.Future<void>.value(),
      ) as _i11.Future<void>);
  @override
  void addListener(_i12.VoidCallback? listener) => super.noSuchMethod(
        Invocation.method(
          #addListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );
  @override
  void removeListener(_i12.VoidCallback? listener) => super.noSuchMethod(
        Invocation.method(
          #removeListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );
  @override
  void dispose() => super.noSuchMethod(
        Invocation.method(
          #dispose,
          [],
        ),
        returnValueForMissingStub: null,
      );
  @override
  void notifyListeners() => super.noSuchMethod(
        Invocation.method(
          #notifyListeners,
          [],
        ),
        returnValueForMissingStub: null,
      );
}
